name: Publish

on:
  push:
    tags:
      - '*.*.*'
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Build
        run: poetry build
      - name: Check distributions
        run: ls -ahl dist
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish