name: Tests
on:
  push:
    paths-ignore:
      - 'README.rst'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'README.rst'
    branches:
      - '**'
jobs:
  Tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --without dev -vvv
      - name: Run tests
        run: |
          poetry run pytest